### ISSUE TITLE
Single Marker Calibration: Add reference

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil-docs#115]
This paper introduces and evaluates this type of calibration. We should reference it!

```
CalibMe: Fast and Unsupervised Eye Tracker Calibration for
Gaze-Based Pervasive Human-Computer Interaction
```

**Comment by cpicanco** [comment]
Nice! https://www.youtube.com/watch?v=gYtF3j2Hdl4

**Comment by papr** [comment]
I added a reference in the source code for now since we do not have a single marker calibration section in the docs yet: pupil-labs/pupil@15f2a89367099cb0e02a37c3b8b89b7da0294e42

**Comment by mkassner** [comment]
@papr  can you add a section in the docs and move the reference to there. I think that is better.

**Comment by mkassner** [comment]
This still needs to be added.

**Comment by nathakits** [comment]
Done with PR https://github.com/pupil-labs/pupil-docs/pull/166.

**Comment by willpatera** [comment]
Merged, closing 😸
