### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil-docs#12]
I would like to update the plugin guide, but I am not sure how to proceed. It is not possible to create tags for pre v092 docs, because this very repository does not have the old wiki history. It is a hard copy of the old wiki. So, should I just forget about the old wiki and make a pull request considering v093 or master?

Also, I have a question. Why using tags instead of using a different branch for each Pupil Version?

**Comment by willpatera** [comment]
Hi @cpicanco - please make all PRs to the `master` branch. 

We use tags to "freeze" versions of docs so that it can correspond to pupil version tags.

**Comment by cpicanco** [comment]
@willpatera , please correct me if I am wrong. AFAIK, pupil-docs **content** will not correspond to pupil tags content if you use pupil-docs tags only. Matching tags is not useful for content matching. For example, right now 0.9.3 pupil-docs has content from earlier versions.

I guess that from 1.0.0 and above pupil-docs should consider to create a new branches for each new version.

**Comment by willpatera** [comment]
@cpicanco - thanks for the feedback. `v0.9.3` pupil-docs does contain some outdated information as does the current `master` branch of pupil-docs. 

The ultimate **goal** is for each new pupil code release to add/update content in the master branch (or in a separate branch that then gets merged with master) and tagged with the release. 

In my opinion a branches are not the right way to go for versioning content in pupil docs. The idea is to constantly update docs and if there is outdated information, fix for the next release or fix in the current master.
