### ISSUE TITLE
Update graphics to match UI updates

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs#120]
Update all graphics to match the new UI.

**Comment by willpatera** [comment]
@nathakits are there other graphics that you are waiting to merge? Otherwise this can be closed with #126

**Comment by nathakits** [comment]
I need to update the `Good eye Bad eye video` callout as well then we can close this issue.

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/pupil-docs/pull/128

**Comment by willpatera** [comment]
@nathakits thanks for the update. I am closing this issue now.
