### ISSUE TITLE
 dev docs - Incorrect hash link - intel realsense 3d

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs#133]
Right now the `installing depencies` section is linking to the wrong realsense 3d link
hash link - #realSense-dependencies - > #realsense-dependencies
Fix - change the hash link to be the same

**Comment by nathakits** [comment]
@willpatera -PR https://github.com/pupil-labs/pupil-docs/pull/134

**Comment by willpatera** [comment]
Merged. Closing.
