### ISSUE TITLE
Update Fixation Detector (User Docs)

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs#145]
Currently on the docs website, in `user-docs` -> `pupil-player` -> `analysis-plugin` -> `[fixation detector](https://docs.pupil-labs.com/master/#fixation-detector-dispersion-duration) plugin is outdated.

@papr - can you please work on the documentation on this section?

**Comment by papr** [comment]
@nathakits Right. This needs to be fixed. But I do not think that repeating stuff from `dev-docs > fixation-detector` would make sense. I would prefer to keep the information in one place. Then again, the `dev-docs` should not be that place.

I see two possibilities:
1. Split the docs for online and offline fixation detector as we have done with the surface tracker docs. They would live in `user-docs >  pupil-capture` and `user-docs >  pupil-player`.
2. Create a new page in the `user-docs` for shared modules and move the fixation detector and surface tracker docs there.

@willpatera @nathakits What do you think about these options? Do you have a third possibility in mind?
