### ISSUE TITLE
No release for suitesparse bugfix on xenial

### ISSUE THREAD

**Issue by wjpjet** [pupil-labs/pupil-docs#149]
16.04 doesn't have a release candidate for this repository:

```
sudo add-apt-repository ppa:bzindovic/suitesparse-bugfix-1319687
sudo apt-get update
sudo apt-get install libsuitesparse-dev
```

`W: The repository 'http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial Release' does not have a Release file.`

**Comment by willpatera** [comment]
@wjpjet `libsuitesparse-dev` should work directly from apt. You can see [build log](https://travis-ci.org/pupil-labs/pupil-docker-ubuntu) for our 16.04 docker image here as example.
