### ISSUE TITLE
Update calibration marker docs

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs#150]

**Comment by willpatera** [comment]
@nathakits please update to the new calibration marker in docs using the new calibration marker from the release: https://github.com/pupil-labs/pupil/releases/tag/v1.2

**Comment by nathakits** [comment]
@willpatera - calibration marker PR - https://github.com/pupil-labs/pupil-docs/pull/153

I wasn't sure if the markers should be separated into two pages or not but now both markers are just on the page.

**Comment by willpatera** [comment]
Merged; closing :smile:
