### ISSUE TITLE
Need to check Boost version dependency 

### ISSUE THREAD

**Issue by sunggeunAhn** [pupil-labs/pupil-docs#151]
(This issue is related to the link: "https://github.com/pupil-labs/pupil/issues/896")

- Dependency error when using Boost which is not 1.6.4 ver
When I try to build "pupil_detector" module with Boost ver 1.6.6 (current latest version), I found there is predefined file path for linking Boost library. This file path is fixed to "boost_python3-vc141-mt-1_64.lib" file. 

I try to find where it is defined at, but I can't find it. 
So I just attached build error log below. 

--------------------------------------------
Unknown compiler version - please run the configure tests and report the results
creating C:\work\pupil\pupil_src\shared_modules\pupil_detectors\build\lib.win-amd64-3.6
creating C:\work\pupil\pupil_src\shared_modules\pupil_detectors\build\lib.win-amd64-3.6\pupil_detectors
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\VC\Tools\MSVC\14.12.25907\bin\HostX86\x64\link.exe 
/nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO 

/LIBPATH:C:\work\boost\stage\lib 
/LIBPATH:C:\Python36\libs /LIBPATH:C:\Python36\PCbuild\amd64 
"/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\VC\Tools\MSVC\14.12.25907\ATLMFC\lib\x64" 
"/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\VC\Tools\MSVC\14.12.25907\lib\x64" 
"/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" 
"/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\VC\Tools\MSVC\14.12.25907\ATLMFC\lib\x86" 
"/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\VC\Tools\MSVC\14.12.25907\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86" 
"/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x86" 
"/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x86" 

/EXPORT:PyInit_detector_2d build\temp.win-amd64-3.6\Release\detector_2d.obj build\temp.win-amd64-3.6\Release\singleeyefitter/ImageProcessing/cvx.obj 
build\temp.win-amd64-3.6\Release\singleeyefitter/utils.obj build\temp.win-amd64-3.6\Release\singleeyefitter/detectorUtils.obj  
C:\work\opencv\build\x64\vc14\lib\opencv_world320.lib  
C:\work\ceres-windows\x64\Release\ceres_static.lib 
C:\work\ceres-windows\x64\Release\libglog_static.lib   
/OUT:build\lib.win-amd64-3.6\pupil_detectors\detector_2d.cp36-win_amd64.pyd 
/IMPLIB:build\temp.win-amd64-3.6\Release\detector_2d.cp36-win_amd64.lib

**LINK : fatal error LNK1104: 'boost_python3-vc141-mt-1_64.lib' 파일을 열 수 없습니다.**
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Professional\\VC\\Tools\\MSVC\\14.12.25907\\bin\\HostX86\\x64\\link.exe' failed with exit status 1104

**Comment by papr** [comment]
Fixed by removing boost dependency in https://github.com/pupil-labs/pupil/pull/1552
