### ISSUE TITLE
For the new developer:  Where are variables seen in output .csv stored during run-time?

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/pupil-docs#152]
I've been exploring what it would take to write a simple plugin for offline fixation detection, and one of the more difficult issues is that it's unclear where variables seen in output *.csv (e.g. gaze positons.csv and pupil_positions.csv) are stored during run-time.

If I've decided to write a fixation detector, how do I know where to get at 'gaze_normal0_x', or 'gaze_normal1_x' ?  Are they part of the g_pool?  Should I get at them through a function like recent_events()?

**Comment by papr** [comment]
We know that the dev docs are not near to be complete but the software changes so often that it is very difficult to maintain correct docs. We prefer no docs over wrong docs. I think it 

The csv files are really just a flat representation of the actual data structures. In Player, you can access pupil and gaze data via the global `g_pool` object. Each `Plugin` instance has a reference to it (`Plugin.g_pool`). These are the lists that include pupil/gaze/fixation data:

- `g_pool.pupil_positions`
- `g_pool.pupil_positions_by_frame`
- `g_pool.gaze_positions`
- `g_pool.gaze_positions_by_frame`
- `g_pool.fixations`
- `g_pool.fixations_by_frame`

P.S.: I suggest calling `dir(g_pool)` to see what other global references are stored there.

**Comment by performlabrit** [comment]
Thanks!

**Comment by willpatera** [comment]
It seems that a sufficient answer has been supplied here in the issue comment by @papr therefore I will close this issue.
