### ISSUE TITLE
Improve Pupil Mobile Documentation

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs#154]
Migrating issue: https://github.com/pupil-labs/pupil-mobile-app/issues/2 here.

Improve Pupil Mobile docs. Show overview of the interface and capabilities of the app with callouts similar to the Pupil Capture and Pupil Player interface overview. 

@nathakits please could you use existing graphics and extend them with callouts as noted above. Reference images of the current state of Pupil Mobile are [here](https://photos.app.goo.gl/5BbhHnU2DIgqphua2)

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/pupil-docs/pull/156

**Comment by willpatera** [comment]
Merged; closing 😄
