### ISSUE TITLE
Update manual calibration marker text

### ISSUE THREAD

**Issue by ChingT** [pupil-labs/pupil-docs#155]
PR #153 
It would be good if the Ref marker and stop marker could be specified clearly in docs and in pdf file, so that the user would not be confusing when using them.
For example, the text on the lower part of the image could be like"Pupil Calibration Ref marker v0.4" for the [Ref marker](https://docs.pupil-labs.com/images/pupil-capture/calibration-markers/v0.4_markers/v0.4_calibration_marker_02.master.jpg), "Pupil Calibration Stop marker v0.4" for the [Stop marker](https://docs.pupil-labs.com/images/pupil-capture/calibration-markers/v0.4_markers/v0.4_calibration_marker_01.master.jpg).

**Comment by willpatera** [comment]
@ChingT yes, this change will be made. I propose that we just use:
- Pupil Calibration Marker v0.4
- Pupil Calibration Stop Marker v0.4

The abbreviation `Ref` and word `Reference` might not be clear to all.

**Comment by nathakits** [comment]
@willpatera - marker PR https://github.com/pupil-labs/pupil-docs/pull/158

**Comment by willpatera** [comment]
Merged; closing 😄
