### ISSUE TITLE
Update section header titles and links for Pupil Mobile user guide

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs#157]
All section permalinks should get pupil-mobile apended or prepended to the link. Example:
`https://docs.pupil-labs.com/#home-screen` --> `https://docs.pupil-labs.com/#pupil-mobile-home-screen`

Updates to headers in Pupil Mobile section
`Recording` --> `Recordings Screen`

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/pupil-docs/pull/159

I also moved the `Close/Quit app` up to number 2. It was in the wrong number.

**Comment by willpatera** [comment]
Merged; closing.
