### ISSUE TITLE
differentiate 200 and 120hz camera systems

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil-docs#161]
200hz system eye cameras can not and do not need to be focused
120hz system is adjustable in focus

**Comment by papr** [comment]
Duplicate of #160, closing

**Comment by mkassner** [comment]
I closed #160

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/pupil-docs/pull/167

Copytext needs checking.

**Comment by willpatera** [comment]
Revised copy text and merged. Closing :smile_cat:
