### ISSUE TITLE
add info about arm extender

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil-docs#163]
Please add render of extender placed between mount and camera arm.

Text:
If you need to adjust the eye cameras beyond the built in adjustment range, you can use the orange arm extenders that are shipped with your Pupil headset. The arm extender slides onto the triangular eye camera rail arm triangle rail and adds a new rail further forward and down. This extender works for all existing 120 and 200hz systems.

Note Aside copy text:
Note: Starting on **2018-02-01** the arm extender is shipped with all Pupil headset orders. If you have an older headset, you can get the extender from our [Shapeways store]( https://www.shapeways.com/product/AP2XV2VNH/pupil-labs-camera-arm-extender-for-120hz-and-200h?optionId=64624597)

**Comment by willpatera** [comment]
@mkassner I edited the copytext above in your comment.

**Comment by nathakits** [comment]
@willpatera - arm extender PR https://github.com/pupil-labs/pupil-docs/pull/164

**Comment by willpatera** [comment]
merged to master; done :smile:
