### ISSUE TITLE
Single Marker Calibration

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs#165]
Add single marker calibraiton section after Manual Marker Calibration Section within [Calibration Methods](https://docs.pupil-labs.com/#calibration-methods). Append note from #115 

Copy text:

Calibrate using a single marker displayed on screen. Gaze at the center of the marker and move your head in a spiral motion. You can also move your head in other patterns. This calibration method enables you to quickly sample a wide range of gaze angles and cover a large range of your FOV.

1. Select Single Marker Calibration
1. Press c on your keyboard or click the blue circular C button on the left hand side of the world window to start calibration.
1. Look at the center of the marker on the screen.
1. Slowly move your head while gazing at the center of the marker. We have found that a spiral pattern is an efficient way to cover a large area of the FOV. 
1. Press the C button on your keyboard to stop calibrating.

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/pupil-docs/pull/166

**Comment by willpatera** [comment]
merged; closing :smile_cat:
