### ISSUE TITLE
calibration section show the stop marker

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil-docs#170]
The manual marker calibration section refers to the stop marker but never shows it. Please add an image of the stop marker below the calibration marker image.

**Comment by willpatera** [comment]
this was removed - can be added back. 

@nathakits please add back the jpg to the sidebar.

**Comment by nathakits** [comment]
PR https://github.com/pupil-labs/pupil-docs/pull/172

**Comment by willpatera** [comment]
merged; closing 😸
