### ISSUE TITLE
Remove Google Group Link

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs#178]
Remove Google Group section - https://github.com/pupil-labs/pupil-docs/blob/master/community/community.md#google-group

**Comment by willpatera** [comment]
This section as well https://github.com/pupil-labs/pupil-docs/blob/master/community/community.md#github has a ref and link to Google Group that can be removed.

**Comment by nathakits** [comment]
@willpatera PR - https://github.com/pupil-labs/pupil-docs/pull/179

**Comment by willpatera** [comment]
merged. closing 😸
