### ISSUE TITLE
Run project

### ISSUE THREAD

**Issue by chopenn** [pupil-labs/pupil-docs#183]
After installing all dependencies on mac I'm running main.py and getting this on my console:

ld: library not found for -lboost_python3
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang++' failed with exit status 1
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/Users/Daniel/Projekty/PupilEyeTracker/pupil/pupil_src/launchables/world.py", line 113, in world
    import pupil_detectors
  File "/Users/Daniel/Projekty/PupilEyeTracker/pupil/pupil_src/shared_modules/pupil_detectors/__init__.py", line 16, in <module>
    build_cpp_extension()
  File "/Users/Daniel/Projekty/PupilEyeTracker/pupil/pupil_src/shared_modules/pupil_detectors/build.py", line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/opt/python3/bin/python3.6', 'setup.py', 'install', '--install-lib=/Users/Daniel/Projekty/PupilEyeTracker/pupil/pupil_src/shared_modules']' returned non-zero exit status 1.

MainProcess - [INFO] os_utils: Re-enabled idle sleep.

**Comment by papr** [comment]
> `ld: library not found for -lboost_python3`

Did you run
```sh
brew install boost
brew install boost-python --with-python3
brew install ceres-solver
```

**Comment by chopenn** [comment]
Yes, i did. This is my first experience with any eye tracker and I hardly understand the idea.  I don't have pupil hardware at home but I've got some recorded files for test purposes. Maybe the problem is that I have to set a file as the input instead of data streaming directly from the device? I can't find any clearful description of the workflow with this hardware and software.

**Comment by papr** [comment]
First of all, I would recommend using our bundled applications from our release page: https://github.com/pupil-labs/pupil/releases

Running from source is only required if you need to make custom changes to the source code. You should use `Pupil Player` If you want to playback an existing recording. Just start the application and drag&drop the recording onto the window.

I also recommend strongly to read the [`Getting Started`section](https://docs.pupil-labs.com/#getting-started) of the docs, in your case specifically the section about Pupil Player.

**Comment by chopenn** [comment]
Thanks for your answers. I have to run it from source because i am going to use it in my project at university. I am going to make simple game with oculographic analysis. How i understood it I have to write a plugin which will be actually the game part of this soft. Is this the right way of doing it?

**Comment by papr** [comment]
I would not recommend this way. Instead you should make your game a stand-alone app that connects to a Pupil Capture instance and subscribes to the gaze data. See this helper script on how to access the data remotely: https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_remote/filter_messages.py

You will also need the surface tracker plugin to define your screen as a surface (using our surface markers) and use the gaze mapped to this surface. This example scripts shows explanatory how to move the mouse based on surface gaze: https://github.com/pupil-labs/pupil-helpers/blob/master/pupil_remote/mouse_control.py

This only works with Pupil Capture. This means that you will need an online source which you do not have access to at the moment.

**Comment by papr** [comment]
Independently, I was able to reproduce a similar setup issue to yours after brew-upgrading `boost` and `python-boost`
```
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "/Users/pabloprietz/work/pupil/pupil_src/launchables/world.py", line 113, in world
    import pupil_detectors
  File "/Users/pabloprietz/work/pupil/pupil_src/shared_modules/pupil_detectors/__init__.py", line 18, in <module>
    from .detector_2d import Detector_2D
ImportError: dlopen(/Users/pabloprietz/work/pupil/pupil_src/shared_modules/pupil_detectors/detector_2d.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/boost-python/lib/libboost_python3.dylib
  Referenced from: /Users/pabloprietz/work/pupil/pupil_src/shared_modules/pupil_detectors/detector_2d.cpython-36m-darwin.so
  Reason: image not found
```

**Comment by papr** [comment]
The initial issue is not a documentation issue but a problem of outdated setup files in the Pupil project. I will close this issue and open it in the correct repository. Please feel free to join [our community channel on Discord](http://pupil-labs.com/chat) and follow up with any questions to your project.

**Comment by papr** [comment]
This was actually a documentation issue in the end. Thank you very much for your contribution! See #184 for a fix.

**Comment by chopenn** [comment]
Works perfectly. Thank you!

**Comment by willpatera** [comment]
Thanks! Merged; closing 😸
