### ISSUE TITLE
Fingertip calibration method graphics

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs#188]
Add docs for fingertip calibration method. 

We should probably include an animation for this method as it would be the easiest way to explain how this method works.

**Comment by willpatera** [comment]
@nathakits a quick static graphic and text for this method would be useful with a warning/note that this is an **experimental** feature.

**Comment by nathakits** [comment]
@willpatera - is this still experimental?

**Comment by willpatera** [comment]
@nathakits yes it is. However generalized documentation on how to use the forthcoming fingertip calibration method could be drafted and merged when ready. 

1. Switch to fingertip calibration method 
1. Check to see that fingertips are detected in world camera view (red dots on fingernails)
1. Pick a finger to use for calibration (e.g. index finger). You will be holding your hand out at arms length and looking at your fingernail.
1. Start calibration
1. Hold your arm still and look at your fingernail. Move head slowly up and down, then left and right. 
1. Stop calibration (show 5 fingers to stop calibration - note this is only available with the new fingertip calibration method).

**Comment by willpatera** [comment]
@nathakits this would be useful to have for `v1.8` release if possible.

**Comment by willpatera** [comment]
closing as fingertip calibration method was removed from the bundle.
