### ISSUE TITLE
Error msgs: "Eye1:Turbopeg jpeg2yuv: b'corrupt premature end of jpeg" AND "overread8"

### ISSUE THREAD

**Issue by kwalders** [pupil-labs/pupil-docs#192]
We received these message numerous times while recording using Capture. We rebooted several times and adjusted the cables and eye 1 camera. Still receiving them. What does this error message mean?

**Comment by cpicanco** [comment]
Please, take a look at https://github.com/pupil-labs/pupil/issues/399

**Comment by mkassner** [comment]
I ll close this since this is not the write place for this issue.
