### ISSUE TITLE
update surface tracker docs

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil-docs#193]
There is a marker that we explicitly exclude from tracking:

![image001](https://user-images.githubusercontent.com/1433767/38414171-01222812-398e-11e8-9630-c2dd433296e0.png)

Please change the pdf to use a different marker (the sheet is not complete so we can pick a different marker that not currently shown as replacement.)

Change the docs and website to say that we track 63 id instead of 64.

**Comment by willpatera** [comment]
@nathakits please work on this update.

**Comment by nathakits** [comment]
@willpatera PR https://github.com/pupil-labs/pupil-docs/pull/194/files

**Comment by willpatera** [comment]
Thanks! Merged #194 closing 😸
