### ISSUE TITLE
FFMPEG version for Windows dependencies installation

### ISSUE THREAD

**Issue by Tonzofdamage** [pupil-labs/pupil-docs#197]
Hello, after struggling through the installation on Windows, I found that the problem was that you need to download FFMPEG 3.4.2 to get the correct version for the 8 dlls. You need to find it in the "previous builds" of the FFMPEG website.

I can't verify for other operating systems, but this fixed my installation.

**Comment by mkassner** [comment]
I just pushed https://github.com/pupil-labs/PyAV/commit/efe19d2e3ae7302d56433165269f68c808032e40 which transitions to ffmepg4.0 PyAV now builds with FFMPEG4.0
