### ISSUE TITLE
add Pupil Mobile offline detection and mapping workflow.

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil-docs#203]
This is currently missing from the docs.

**Comment by nathakits** [comment]
Todo - Revising the copy text for the section on pupil mobile to include information about how it is possible to:
(1) record on the android device and 
(2) perform pupil detection, and gaze estimation - calibration - post-hoc with Pupil Player.

**Comment by nathakits** [comment]
Note - we should also update the `Offline pupil detection and gaze mapping` and `Offline gaze mapping with natural features` videos with the latest version of Player.

**Comment by nathakits** [comment]
WIP branch - https://github.com/nathakits/pupil-docs/tree/mobile_workflow

**Comment by papr** [comment]
Please do not create new videos for the workflow yet!

I am currently refactoring the offline calibration plugin such that users can import existing calibrations as well as validate calibrations using the accuracy visualizer.

I will comment on this issue as soon as I have a working prototype.

**Comment by nathakits** [comment]
@papr any updates?

**Comment by papr** [comment]
Hey @nathakits,
unfortunately not, since I am prioritizing the deferred serialization feature at the moment. Currently it looks like the refactor will have to wait for the next release.

**Comment by nathakits** [comment]
Okay noted.

**Comment by papr** [comment]
Fixed in https://github.com/pupil-labs/pupil-docs/pull/238
