### ISSUE TITLE
Fingertip Calibration Developer Dependencies

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs#207]
Add dependencies required to build fingertip detector (torch, torchvision)

**Comment by willpatera** [comment]
Linux dependencies completed with #208 

TODO:
- [ ] macos dependencies - @mkassner 
- [ ] windows dependencies - (me)

**Comment by papr** [comment]
Fixed in https://github.com/pupil-labs/pupil-docs/pull/226 and https://github.com/pupil-labs/pupil-docs/pull/259
