### ISSUE TITLE
Could not get hardware ID

### ISSUE THREAD

**Issue by avivelor** [pupil-labs/pupil-docs#213]
Hi all,

I've just started to use the Pupil Mobile Eye Tracking Headset and I can't seem to get any of the cameras to connect to Pupil Capture on Windows 10. However, when running the mobile app, I do get all cameras. I have made sure to follow the "Getting Stared Guide" (https://docs.pupil-labs.com/#getting-started). Does anyone have any ideas to what's going on?

Thank you for your time!

---Terminal Info---
Version: 10.0.17134
Running  PupilDrvInst.exe --vid 1443 --pid 37424
OPT: VID number 1443
OPT: PID number 37424
libwdi:error [wdi_create_list] could not get hardware ID
Running  PupilDrvInst.exe --vid 1443 --pid 37425
OPT: VID number 1443
OPT: PID number 37425
libwdi:error [wdi_create_list] could not get hardware ID
Running  PupilDrvInst.exe --vid 1443 --pid 37426
OPT: VID number 1443
OPT: PID number 37426
libwdi:error [wdi_create_list] could not get hardware ID
Running  PupilDrvInst.exe --vid 1133 --pid 2115
OPT: VID number 1133
OPT: PID number 2115
libwdi:error [wdi_create_list] could not get hardware ID
Running  PupilDrvInst.exe --vid 6127 --pid 18447
OPT: VID number 6127
OPT: PID number 18447
libwdi:error [wdi_create_list] could not get hardware ID
Running  PupilDrvInst.exe --vid 3141 --pid 25771
OPT: VID number 3141
OPT: PID number 25771
libwdi:error [wdi_create_list] could not get hardware ID
world - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.
world - [INFO] camera_models: No user calibration found for camera Ghost capture at resolution [1280, 720]
world - [INFO] camera_models: No pre-recorded calibration available
world - [WARNING] camera_models: Loading dummy calibration
world - [WARNING] launchables.world: Process started.

**Comment by willpatera** [comment]
@avivelor this seems like it could be driver related. I know that this issue was posted a long time ago. Have you tested the latest Pupil Capture application bundles and run as administrator?
