### ISSUE TITLE
Update docs for DIY camera drivers.

### ISSUE THREAD

**Issue by gmierz** [pupil-labs/pupil-docs#216]
To me there isn't enough information in the docs about driver installation for DIY cameras or fixing the drivers if they break so I've made some changes in PR #215 that could be added to the docs which could address this problem. It would make it simpler for people to find this troubleshooting information. I say this because it took me a good bit of time to find this information the second time around. @willpatera it is based on the information you provided in this issue: https://github.com/pupil-labs/pupil/issues/1011#issuecomment-360345338

Would this be something that could be added?

**Comment by willpatera** [comment]
Thanks @gmierz merged with #215 - closing :smile_cat:
