### ISSUE TITLE
It seems "Pupil Docs -v0.9.4" does not work well.

### ISSUE THREAD

**Issue by saki4510t** [pupil-labs/pupil-docs#22]
When I click menu item like `Getting Started` from menu list placed on left, it opened but sometimes immediately closed and I can not select any child item. And when I scroll down the main frame, I can see the child menu items.  Some items can be open when I click but some items can not. This occurs when the width of browser is smaller than a specific value.
Is this behavior normal?

**Comment by willpatera** [comment]
What width do you experience this issue?

**Comment by saki4510t** [comment]
Around 1000px.
This occurs on Safari on OSX but not always. I will try to confirm.

**Comment by willpatera** [comment]
Thanks - I will take a look.

**Comment by willpatera** [comment]
@saki4510t - I am not able to reproduce this issue unfortunately.

**Comment by saki4510t** [comment]
Hi @willpatera 
I will share you short movie that how this issue looks although I'm still not sure how and when this issue occur.
https://drive.google.com/file/d/0B9UWnsrc86YGUjZseUN4VV9tc3c/view?usp=sharing
