### ISSUE TITLE
More information regarding world camera Intrinsic Matrix

### ISSUE THREAD

**Issue by RSKothari** [pupil-labs/pupil-docs#221]
Per my discussion with @papr , we need more information in the docs regarding the Intrinsic Matrix Pupil player chooses. The docs should also reflect the different conditions for which a prerecorded camera matrix exists. A helpful note would be to instruct people how to add their own Intrinsic Matrices in recorded data.

**Comment by willpatera** [comment]
@papr Has this already been done? Or still open issue?
