### ISSUE TITLE
run_capture.bat not working

### ISSUE THREAD

**Issue by mehranhussain** [pupil-labs/pupil-docs#222]
C:\work\pupil\pupil_src>python main.py capture
world - [INFO] launchables.world: Application Version: 1.8.108
world - [INFO] launchables.world: System Info: User: mehran, Platform: Windows, Machine: automaton, Release: 10, Version: 10.0.17134
world - [INFO] pupil_detectors.build: Building extension modules...
cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Community\\VC\\Tools\\MSVC\\14.16.26926\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "C:\work\pupil\pupil_src\launchables\world.py", line 113, in world
    import pupil_detectors
  File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors\__init__.py", line 16, in <module>
    build_cpp_extension()
  File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors\build.py", line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "C:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Python36\\python.exe', 'setup.py', 'install', '--install-lib=C:\\work\\pupil\\pupil_src\\shared_modules']' returned non-zero exit status 1.

world - [INFO] launchables.world: Process shutting down.

**Comment by eicm** [comment]
@mehranhussain were you able to resolve your issue?
