### ISSUE TITLE
Hardware schematics

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs#225]
It would be great to have high-level schematics for the different hardware parts. This way users can be more specific when describing issues. The technical support can also give more detailed instructions to users if required.

**Comment by willpatera** [comment]
Yes, this is a good point @papr - we should have a more clear diagram of names of parts for the hardware.

**Comment by willpatera** [comment]
@papr this has been added already with callouts in /core/hardware and /invisible/hardware. Closing :smile_cat:
