### ISSUE TITLE
Add note on Python Wheels

### ISSUE THREAD

**Issue by Windsooon** [pupil-labs/pupil-docs#232]
This docs at [python-wheels](https://docs.pupil-labs.com/#python-wheels) may be confusing to people who are not familiar with pip. We provide the pip3 example:
```
pip3 install PyOpenGL
pip3 install pyzmq 
```
But in the documents, we use pip instead

> Install all wheels with pip install X (where X is the name of the .whl file)
later.

One of the solutions would change all pip to pip3 in the document, another solution would add a note explaining if users installed both python2 and python3, they should run pip3 instead of pip.

**Comment by papr** [comment]
> Install all wheels with pip install X (where X is the name of the .whl file)
later.

This is part of the Windows dependency instructions. There is no `pip3` on Windows, just `pip`.
