### ISSUE TITLE
Setup instruction of ceres-windows for Windows, step 5 is wrong.

### ISSUE THREAD

**Issue by saki4510t** [pupil-labs/pupil-docs#24]
Setup instruction of ceres-windows for Windows, step 5 is
> Open the vs2012 sln file using VS2015. Agree to upgrade the compiler and libraries.

As I download now, ceres-windows repository includes  `ceres-2010.sln`,  `ceres-2012.sln`, `ceres-2015.sln` now. I assume the `sln` file on step 5 is  `ceres-2015.sln` instead of `vs2012.sln`.

**Comment by willpatera** [comment]
I am re-writing the install instructions and testing simultaneously. The update should be ready by tomorrow with python3.6.

**Comment by willpatera** [comment]
Resolved. See: https://github.com/pupil-labs/pupil-docs/issues/30#issuecomment-310280600
