### ISSUE TITLE
Which version of OpenCV should I use?

### ISSUE THREAD

**Issue by saki4510t** [pupil-labs/pupil-docs#25]
As instruction says on `Python Wheels` section,
> OpenCV: opencv_python-3.1.0-cp35-cp35m-win_amd64.whl

but this is not available now and current pre-build opencv_python packages by Christoph Gohlke is as follows;
```
opencv_python‑2.4.13.2‑cp27‑cp27m‑win32.whl
opencv_python‑2.4.13.2‑cp27‑cp27m‑win_amd64.whl
opencv_python‑3.1.0‑cp27‑cp27m‑win32.whl
opencv_python‑3.1.0‑cp27‑cp27m‑win_amd64.whl
opencv_python‑3.1.0‑cp34‑cp34m‑win32.whl
opencv_python‑3.1.0‑cp34‑cp34m‑win_amd64.whl
opencv_python‑3.2.0+contrib‑cp35‑cp35m‑win32.whl
opencv_python‑3.2.0+contrib‑cp35‑cp35m‑win_amd64.whl
opencv_python‑3.2.0+contrib‑cp36‑cp36m‑win32.whl
opencv_python‑3.2.0+contrib‑cp36‑cp36m‑win_amd64.whl
opencv_python‑3.2.0‑cp35‑cp35m‑win32.whl
opencv_python‑3.2.0‑cp35‑cp35m‑win_amd64.whl
opencv_python‑3.2.0‑cp36‑cp36m‑win32.whl
opencv_python‑3.2.0‑cp36‑cp36m‑win_amd64.whl
```

So I assume if we want to use python 3.5 and opencv with pre-build package, we need to use `opencv_python‑3.2.0‑cp35‑cp35m‑win_amd64.whl` package but this is for OpenCV 3.2 instead of OpenCV 3.1...

Then which OpenCV should I use?

**Comment by willpatera** [comment]
opencv_python‑3.2.0‑cp35‑cp35m‑win_amd64.whl

Should also be compatible.

**Comment by saki4510t** [comment]
I think so and I already tried with OpenCV 3.2. But still can not run `run_capture.bat` with #30.

**Comment by willpatera** [comment]
Resolved. See: https://github.com/pupil-labs/pupil-docs/issues/30#issuecomment-310280600
