### ISSUE TITLE
Which version of boost should I use?

### ISSUE THREAD

**Issue by saki4510t** [pupil-labs/pupil-docs#26]
As instruction Python Wheels says;
> boost_python: boost_python-1.59-cp35-none-win_amd64.whl

But current available pre-build whl packages by Christoph Gohlke are;

```
boost_python‑1.63‑cp27‑cp27m‑win32.whl
boost_python‑1.63‑cp27‑cp27m‑win_amd64.whl
boost_python‑1.63‑cp34‑cp34m‑win32.whl
boost_python‑1.63‑cp34‑cp34m‑win_amd64.whl
boost_python‑1.63‑cp35‑cp35m‑win32.whl
boost_python‑1.63‑cp35‑cp35m‑win_amd64.whl
boost_python‑1.63‑cp36‑cp36m‑win32.whl
boost_python‑1.63‑cp36‑cp36m‑win_amd64.whl
```
and all of them are for boost 1.63.

**Comment by willpatera** [comment]
Dependency versions are fast changing. Please try:
boost_python‑1.63‑cp35‑cp35m‑win_amd64.whl

**Comment by willpatera** [comment]
Resolved. See: https://github.com/pupil-labs/pupil-docs/issues/30#issuecomment-310280600
