### ISSUE TITLE
Eigen directory

### ISSUE THREAD

**Issue by saki4510t** [pupil-labs/pupil-docs#27]
Setup instruction of ceres-windows for Windows says;
 
> Copy the Eigen directory to ceres-windows

Current file name of compressed eigen library from download link of `Pupil Docs v0.9.4` is  `eigen-eigen-b9cd8366d4e8.zip` and the default extracting directory name is `eigen-eigen-b9cd8366d4e8`.
So we should rename it to `eigen` before move to `ceres-windows` directory otherwise we can not correctly compile/build libraries.

**Comment by willpatera** [comment]
Resolved. See: https://github.com/pupil-labs/pupil-docs/issues/30#issuecomment-310280600
