### ISSUE TITLE
Libuvc windows build instructions are out of date.

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pupil-docs#272]
NOTE: The current master of libuvc does not build on windows out of the box anyways.
On commit [b394ccc6bac7a26bcf3391c3a1fbf071da789a3b](https://github.com/pupil-labs/libuvc/tree/b394ccc6bac7a26bcf3391c3a1fbf071da789a3b).
Until this is not fixed, we shouldn't work on this issue here.

---

There are some issues with the docs at https://docs.pupil-labs.com/#libuvc :

- [ ] `LIBUSB_LIBRARY_NAMES` does not exist anymore, but is now called `LIBUSB_LIBRARIES`
- [ ] `PTHREAD_LIBRARY_NAMES` does not exist anymore, but is now called `PTHREAD_LIBRARIES`
- [ ] The LIBUSB path links to `C:\work\libusb\x64\Release\dll\libusb-1.0.lib`, but the libusb build instructions above (https://docs.pupil-labs.com/#libusb) mention to build libusb as static library, which will result in the library being placed in ...\Release\\**lib**\\... instead of ...\Release\\**dll**\\...
- [ ] CMake uses forward slashes also on windows, but the docs have backslashes.

We should investigate why current master does not build and make the necessary changes and then update the docs to reflect the above issues plus all others that arise while making it build again.

**Comment by willpatera** [comment]
@pfaion I'm closing this as it should be included in /pupil-labs/pupil repo or directly in /pupil-labs/pyuvc repo.
