### ISSUE TITLE
missing instruction for msgpack

### ISSUE THREAD

**Issue by saki4510t** [pupil-labs/pupil-docs#28]
After following setup instruction for Windows on`Pupil Docs v0.9.4` and run `run_capture.bat` generate error
```
c:\temp\pupil\pupil_src\capture>python main.py
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    import zmq_tools
  File "c:\temp\pupil\pupil_src\shared_modules\zmq_tools.py", line 19, in <module>
    import msgpack as serializer
ImportError: No module named 'msgpack'
```

So it needs `pip install msgpack-python` on instruction.

**Comment by willpatera** [comment]
Resolved. See: https://github.com/pupil-labs/pupil-docs/issues/30#issuecomment-310280600
