### ISSUE TITLE
AssetionError  assert pyglui_version >= '1.3'

### ISSUE THREAD

**Issue by saki4510t** [pupil-labs/pupil-docs#29]
Running `run_capture.bat `after following setup instruction in `Developers Docs` on `Pupil Docs v0.9.4`, it generates

```
C:\temp\pupil\pupil_src\capture>python main.py
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
Process world:
Traceback (most recent call last):
  File "C:\Users\saki\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\saki\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\temp\pupil\pupil_src\capture\world.py", line 76, in world
    assert pyglui_version >= '1.3'
AssertionError
```

because the latest release version of `pyglui` from download link is `1.2`.
(source of 1.3 is available now though)

**Comment by willpatera** [comment]
We can add a wheel for v1.3 - thanks.

**Comment by saki4510t** [comment]
I tried to use v1.3 from source and this error disappeared but I still can not run `run_captre.bat` with #30

**Comment by et939651** [comment]
Hi, I have the exactly same issue. Could you publish v1.3 wheel?

**Comment by willpatera** [comment]
Published. Please see comment here: https://github.com/pupil-labs/pupil-docs/issues/30#issuecomment-310280600
