### ISSUE TITLE
h4/h5 title links inconsistency

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs#291]
Even though, hovering an h4/h5 title shows a `#` to link the title (see screenshot), clicking on will produce inconsistent behaviour:
1. The webpage will jump to the location, the URL bar shows the correct link for a fraction of a second
2. The URL bar switches to the next highest title, without moving the webpage

Expected behaviour: 1. without 2.

![Screenshot 2019-09-24 at 16 25 06](https://user-images.githubusercontent.com/168390/65520656-3a18e600-dee8-11e9-9bc4-a8d046327b46.png)

This makes it difficult to deep-link specific parts of the documentation.

**Comment by willpatera** [comment]
Never use h5, closing wontfix.
