### ISSUE TITLE
.v-btn__content text centered vertically (visually)

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs#295]
Even though the text element of `.v-btn__content` is centered vertically...

![Screenshot 2019-09-25 at 10 00 22](https://user-images.githubusercontent.com/168390/65581239-6b8ec180-df7b-11e9-8aa0-8c2c708185a7.png)

...the text is not, since it is all uppercase.

![Screenshot 2019-09-25 at 09 58 40](https://user-images.githubusercontent.com/168390/65581328-8c571700-df7b-11e9-8e67-7a2a299ad036.png)

**Comment by nathakits** [comment]
I think it's because of the line-height of the text. I can investigate and fix this.

**Comment by willpatera** [comment]
@nathakits this is really and low priority. I will close this now.
