### ISSUE TITLE
Mismatching warning colors

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs#296]
```markdown
::: warning
<v-icon large color="warning">info_outline</v-icon>
:::
```
... generates ...

![Screenshot 2019-09-25 at 11 47 34](https://user-images.githubusercontent.com/168390/65590002-50777e00-df8a-11e9-9456-62284f8f10ad.png)

The corresponding css colors:
```css
.custom-block.warning { border-color: #e7c000; }
.warning--text { color: #fb8c00; }
```

**Comment by nathakits** [comment]
Resolved
