### ISSUE TITLE
Embed PI network example as Gist

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs#305]
@willpatera IIRC you mentioned that it is possible to embed gists? I would like to do that with the https://docs.pupil-labs.com/developer/invisible/#network-api example.

**Comment by willpatera** [comment]
@nathakits can you make a component to render gists? Should be simple async ajax call to get the content then wrap in `<pre class="language-XX">` (where XX is the language suffix). 

Example component spec

```
<gist
:src="https://gist.github.com/willpatera/e8a338d8f97bd139d21d9405f66c6d4f
class="language-py"
>
</gist>
```

**Comment by willpatera** [comment]
Closing. I do not want to implement this for docs.
