### ISSUE TITLE
Edit This Page: links are broken

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pupil-docs#310]
Getting a GitHub 404.
The links seem to link to the **vuepress-refactor** branch instead of **master**.

https://github.com/pupil-labs/pupil-docs/edit/vuepress-refactor/src/developer/README.md

![image](https://user-images.githubusercontent.com/7101194/66300606-df26bc00-e8f5-11e9-8802-13809497393f.png)

**Comment by nathakits** [comment]
Made a PR to fix this issue - https://github.com/pupil-labs/pupil-docs/pull/311

**Comment by willpatera** [comment]
Fixed with #311
