### ISSUE TITLE
Fix calibration marker download link

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs#34]
Currently the path to the pdf is incorrect - 
`https://docs.pupil-labs.com/images/calibration-markers/pupil_calibration_marker.v093.pdf`

The path is missing `/pupil-capture` . The correct path to the pdf should be this -> 
`https://docs.pupil-labs.com/images/pupil-capture/calibration-markers/pupil_calibration_marker.<version>.pdf`

**Comment by willpatera** [comment]
@nathakits - did you fix this already?

**Comment by nathakits** [comment]
Apologies, just fixed. PR - https://github.com/pupil-labs/pupil-docs/pull/38
