### ISSUE TITLE
Offline surface tracker docs are outdated

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pupil-docs#370]
I just realized that all of this is completely out of date:
https://docs.pupil-labs.com/core/software/pupil-player/#offline-surface-tracker

**Comment by pfaion** [comment]
Maybe it would be better to actually have a menu entry about the surface tracker. This is all grouped under **Analysis Plugins**, whereas in Capture there is dedicated **Surface Tracking** menu entry.

**Comment by willpatera** [comment]
I will close this as it is more of feedback item than issue. I think surface tracker docs should be up to date. @papr or @N-M-T please re-open if that is not the case.
