### ISSUE TITLE
Clicking the menu does not scroll back to the top

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pupil-docs#373]
When in a very long section, e.g: https://docs.pupil-labs.com/core/software/pupil-capture/#calibration-methods and scrolling down a bit, I cannot go back to the top of the section when I click on **Calibration Methods** in the sidebar menu. I find that confusing.

**Comment by pfaion** [comment]
These links will be broken once #377 is merged. Need to update.

**Comment by willpatera** [comment]
Feedback item. Let's track this in CU.
