### ISSUE TITLE
Word wraps break up `code text` and punctuation

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pupil-docs#374]
See in this screenshot:
![image](https://user-images.githubusercontent.com/7101194/83884205-d9170280-a744-11ea-8424-7c9706e3d037.png)
The dot (.) is not attached to the `formatted text`. GitHub seems to handle that correctly.

**Comment by nathakits** [comment]
Is this the behavior you are expecting?

![docs pupil-labs com_core_software_pupil-capture_](https://user-images.githubusercontent.com/17331040/90622161-f422ea00-e23e-11ea-8664-5edc89d1e9b6.png)

**Comment by pfaion** [comment]
I guess so. Specifically I would expect the dot (.) to be always bound to the `Marker`. So it should be either

use the `Pupil Calibration Marker`.

or

use the `Pupil Calibration`
`Marker`.

but never

use the `Pupil Calibration Marker`
.

**Comment by nathakits** [comment]
The HTML markup from the docs site and GitHub is identical. So in the markup it is not bound together but updating the CSS it can make it look like it is bound. I will make a PR for this.
