### ISSUE TITLE
Broken link to blog post

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pupil-docs#376]
See this section: https://docs.pupil-labs.com/core/software/pupil-capture/#further-functionality

> ... See our [blog post](https://pupil-labs.com/news/0392-release) for more information.

I get a 404 with this link.
No idea where to get the correct link from though.

**Comment by willpatera** [comment]
@pfaion - let's not link to old blog post. Link to data format for exported data for surfaces.

**Comment by willpatera** [comment]
This has been resolved. Closing.
