### ISSUE TITLE
Run pupil player and export data from a command line

### ISSUE THREAD

**Issue by jlalexie1** [pupil-labs/pupil-docs#456]
Hello,
I run the pupil player program from another VB program with the command line X: \ Pupil Player v3.4.0 "Path to recording folder". It works and the pupil player window appears. Then I click on the export icon to export.
Is there a way to start the export from the command line?
I tried  X: \ Pupil Player v3.4.0 "Path to recording folder" -e, but it don't work.
Thank you.

**Comment by willpatera** [comment]
Hi 👋🏼 
There is not currently a CLI for Pupil Player aside from starting the app and opening recordings. @papr perhaps you can elaborate.

**Comment by jlalexie1** [comment]
Thank you for the answer.
