### ISSUE TITLE
Recording folder hierarchy not displayed correctly

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs#55]
System: Ubuntu 16.04
Browser: Chrome 57.0.2987.110

Screenshot how hierarchy is rendered on [docs.pupil-labs.com](https://docs.pupil-labs.com/#5-record):
![screenshot from 2017-05-30 09-11-34](https://cloud.githubusercontent.com/assets/168390/26571965/6b1fdf36-4518-11e7-97b8-7b8a11988b54.png)

Screenshot how raw markdown is rendered on Github
![screenshot from 2017-05-30 09-11-51](https://cloud.githubusercontent.com/assets/168390/26571966/6b221efe-4518-11e7-9ec8-4b4c5290c63e.png)

**Comment by willpatera** [comment]
@nathakits this looks like a css issue.

**Comment by nathakits** [comment]
@papr  - Looks like its a markdown renderer issue. This uses Blackfriday Markdown which is different to what Github uses. Using tabs of 4 spaces renders the nested level correctly.

 https://github.com/russross/blackfriday/issues/329

**Comment by nathakits** [comment]
PR - https://github.com/pupil-labs/pupil-docs/pull/57
