### ISSUE TITLE
Fix missing alt tags 

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs#59]
Build the site locally to debug and fix images with missing alt tags. Working only on master branch.

**Comment by nathakits** [comment]
PRs - 
added alt text for images - https://github.com/pupil-labs/pupil-docs/pull/58
added alt tag parameter for images - https://github.com/pupil-labs/docuapi/pull/28/files

**Comment by willpatera** [comment]
Merged. Closing.
