### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs#60]
Build the site locally to debug and fix broken links. Working only on master branch.

**Comment by nathakits** [comment]
**PR** 

broken links and id tags
https://github.com/pupil-labs/pupil-docs/pull/61

Also made fix for div tag error in `baseof.hmtl`
https://github.com/pupil-labs/docuapi/pull/29

**Comment by willpatera** [comment]
One minor change required for #61 

https://github.com/pupil-labs/docuapi/pull/29 was already merged.

**Comment by nathakits** [comment]
All PRs merged. Closing issue.
