### ISSUE TITLE
Missing section about camera calibration

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs#70]
As noted by @anligert in pupil-labs/pupil#748 this section has been available in the wiki but is missing now.

**Comment by willpatera** [comment]
@nathakits can you please revive this section from the old Pupil wiki?

**Comment by nathakits** [comment]
@papr - I'm having trouble finding this section in Pupil wiki docs. Do you remember what this section looks like in the wiki?

**Comment by papr** [comment]
No, not exactly. But it should contain information about the usage of a checkboard pattern. This section should include information on the new fish eye calibration and how it is different to the normal camera calibration (dev docs part, @mt should be able to write some sentences about that) and the user docs instructions that explains why this step is crucial for good mapping, how to do it (usage of checkboard pattern, link to Opencv tutorial/docs), and a link to the Intel Realsense Camera Calibrator for people that use the 3d camera (this is an additional step for now, it does not replace the usage of the camera calibration plugin)

**Comment by Tobias-Fischer** [comment]
Hi, is there any news on this? I need this quite urgently - a copy of the old Pupil wiki docs would be good enough.

Thanks, Tobi

**Comment by willpatera** [comment]
Hi @Tobias-Fischer apologies for the delay. 

I searched the old wiki and did not find the section on calibration of the camera. You are also welcome to take a look at `git clone https://github.com/pupil-labs/pupil.wiki.git` - The process is quite simple, and we can add docs on this today. 

@papr calibrating the RealSense is a separate issue.

**Comment by nathakits** [comment]
@willpatera - draft PR - https://github.com/pupil-labs/pupil-docs/pull/96

**Comment by willpatera** [comment]
Closed with #96 - will be available in docs.pupil-labs.com/master

**Comment by Tobias-Fischer** [comment]
Great, thanks!

**Comment by nathakits** [comment]
@Tobias-Fischer - the docs is here -> https://docs.pupil-labs.com/master/#camera-intrinsics-estimation

**Comment by papr** [comment]
This section will need some further information on the upcoming model-based intrinsics esimation changes. I will talk to @marc-tonsen about it.
