### ISSUE TITLE
player software doesn't start/open

### ISSUE THREAD

**Issue by FrancoisEN** [pupil-labs/pupil-docs#78]
I have an issue concerning the start of the player software. It crashes immediately. 

This is among others the message => Player [warning]: you did not supply a data directory when you called this script! 

What to do? Thanks. 
![image](https://user-images.githubusercontent.com/30172482/28205522-b0d88176-6882-11e7-8ee4-6d8d6fe03b70.png)

**Comment by willpatera** [comment]
@FrancoisEN please open pupil_player.exe then drag a data recording folder (e.g. a folder labeled `000` that contains world video and pupil_data file).

**Comment by willpatera** [comment]
@FrancoisEN I hope that this resolved your issue. I will close this issue now. Please comment if you have not resolved your issue.
