### ISSUE TITLE
new Hololens setup section

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs#82]
Create new Hololens setup section with animations and explainations

**Comment by nathakits** [comment]
@willpatera - Hololens animation PR 
https://github.com/pupil-labs/pupil-docs/pull/81

**Comment by willpatera** [comment]
@nathakits #81 was merged. Please draft a section within Pupil Hardware titled HoloLens Setup. Please set the weight of this section to appear after the Oculus DK2 Setup (weight= 3.2). 

Sections titles are:

### Install cameras
Snap the orange parts of the eye camera mounts into the HoloLens frame. 

The World camera is attached to the top of the HoloLens with tape.

### Route cables
Route cables along the inside of the HoloLens frame. Use tape to attach the cable to the HoloLens frame.

**Comment by nathakits** [comment]
@willpatera - HoloLens docs PR - https://github.com/pupil-labs/pupil-docs/pull/83

**Comment by nathakits** [comment]
Merged. Closing.
