### ISSUE TITLE
Good and bad eye image example

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs#86]
Add example of a "good" and "bad" eye image in the getting started section. This section should link to other areas of the docs so that users know how to adjust the cameras and focus the cameras.

**Comment by willpatera** [comment]
I will create these images.

**Comment by nathakits** [comment]
@willpatera - PR - https://github.com/pupil-labs/pupil-docs/pull/104

**Comment by nathakits** [comment]
@willpatera - PR - https://github.com/pupil-labs/pupil-docs/pull/105

**Comment by willpatera** [comment]
Merged #105 - closing.
