### ISSUE TITLE
Add content to Pupil Mobile docs

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs#89]
Right now the docs on Pupil Mobile is very limited. Hopefully additional information will help users understand the app more and on how to use it. 

Here are some of the contents to be added to the Pupil Mobile docs.

1. Streaming to clients
     - select as source in Capture
2. Wifi Bandwidth / Network
     - local wifi network
     - firewall
3. UDP transport
4. Internals of the app

**Comment by nathakits** [comment]
Referencing from pupil mobile issue - https://github.com/pupil-labs/pupil-mobile-app/issues/2

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/pupil-docs/pull/103

**Comment by willpatera** [comment]
Merged with #103
