### ISSUE TITLE
Offline Calibration Videos

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs#92]
Offline Calibration video links are broken - https://docs.pupil-labs.com/master/#data-source-plugins (scroll down to offline calibration

**Comment by papr** [comment]
The links themselves seem to be ok. They are referenced well in the markdown file:
https://github.com/pupil-labs/pupil-docs/blob/master/user-docs/pupil-player.md#offline-calibration

**Comment by papr** [comment]
Maybe the links need to be changed from `https://www.youtube.com/watch?v=lPtwAkjNT2Q` to
`https://www.youtube.com/embed/lPtwAkjNT2Q`

**Comment by willpatera** [comment]
yes, it needs to be an embed link like this: https://github.com/pupil-labs/pupil-docs/blob/master/pupil-hardware/htc-vive-add-on-setup.md#a-detailed-look

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/pupil-docs/pull/95

**Comment by willpatera** [comment]
Merged https://github.com/pupil-labs/docuapi/pull/39 and merged https://github.com/pupil-labs/pupil-docs/pull/95
